keys:
  - &admin_poisonphang b57a443139b74db6150e9b490ab4dacfbb1e58aa
  - &server_testnet-val-poisonphang 4e6f79cc930e5ad5b97b91529b0b50f8ffb4fb34
  - &server_testnet-seed-poisonphang 353ab4b81cfde25a378e1947a7327fbf58bc3e7f
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|key)$
    key_groups:
    - pgp:
      - *admin_poisonphang
      - *server_testnet-val-poisonphang
      - *server_testnet-seed-poisonphang
  - path_regex: secrets/beefy-sausage/[^/]+\.(yaml|json|env|ini|key)$
    key_groups:
    - pgp:
      - *admin_poisonphang
      - *server_testnet-val-poisonphang
      - *server_testnet-seed-poisonphang
